#!/bin/bash
echo "// DON'T EDIT: automatically generated by ../scripts/make_skills_registry.sh"
echo "use actor::Actor;"
echo "use plan::Plan;"
echo "use skills::*;"
echo "use world::World;"
echo ""
echo "#[allow(warnings)]"
echo "pub fn choose_skill(actor: &mut Actor, wld: &World, p: &Plan) -> bool {"
grep --color=never -o 'pub fn can_[a-z_]*' ./src/skills.rs|awk -F 'can_' '{print $2}' | while IFS= read -r skill; do
    echo "    choose_skill!(should_$skill if can_$skill => actor, wld, p);"
done
echo "    false";
echo "}"
echo ""
echo "#[allow(warnings)]"
echo "pub fn use_skill(actor: &mut Actor, wld: &mut World, p: &Plan, spawn: &mut Vec<Actor>) {"
grep --color=never -o 'pub fn can_[a-z_]*' ./src/skills.rs|awk -F'can_' '{print $2}' | while IFS= read -r skill ; do
    echo "    use_skill!($skill if can_$skill => actor, wld, p, spawn);"
done
echo "}"
