name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sudo apt-get install libncurses5-dev libncursesw5-dev; cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --nocapture
