name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get install libncurses5-dev libncursesw5-dev
        cargo build --verbose
    - name: Test
      run: |
        cargo test --verbose -- --nocapture
